### PR TITLE
Fix malloc placeholder

### PR DESCRIPTION
**Pull request by tgymnich**

### CODE REVIEW

**Review by wsmoses — APPROVED** [review]
Add a test otherwise lgtm

**Comment by tgymnich** [comment]
> Add a test otherwise lgtm

I still need to do something like #251

**Comment by wsmoses** [comment]
I don't think you do? Reverse needs to keep around allocations from fwd to reverse, but forward mode should be able to get away with doing the same allocation/deallocation as the original program

**Comment by tgymnich** [comment]
I just want to handle `enzyme_fromstack`

**Comment by wsmoses** [comment]
Oh, `enzyme_fromstack` shouldn't be enabled for forward mode

**Comment by tgymnich** [comment]
It is

**Comment by wsmoses** [comment]
We'll there's the solution to the problem!

**Pull request merged**
