### PR TITLE
Distribute minimal source archives

### PR DESCRIPTION
**Pull request by nbren12**
It takes a while to check out this repo, which is quite large. Uncompressed the repo size is 2 GB, which makes it a bit slow to build dockerfiles with. To cut down on the initial download for users, this PR sets git attributes such that only the files within the `enzyme` subdirectory are exported with `git-archive`. The `enzyme/benchmarks` folder is also ignored since it is quite large. The resulting tar file is <1 MB in size.

See #119.

### CODE REVIEW

**Comment by wsmoses** [comment]
It looks like your cmake change isn't finding the benchmark directory?

**Comment by nbren12** [comment]
Thanks @wsmoses. I'll look into it. Nice set of tests!

**Comment by vchuravy** [comment]
Closed in favour of #135 thanks @nbren12

**Comment by nbren12** [comment]
Sounds good. Thanks @vchuravy.  This "CI apocalypse" sounds grim haha.

**Pull request closed without merging**
