### PR TITLE
added link to Rust bindings to readme

### PR DESCRIPTION
**Pull request by nestordemeure**
Added a link to unofficial Rust bindings to make them easier to locate.

### CODE REVIEW

**Comment by wsmoses** [comment]
@ZuseZ4 ready to "release"?

If so, mind also making a PR to the www branch (which hosts the website enzyme.mit.edu)

**Comment by ZuseZ4** [comment]
I would like to postpone it for the weekend, to fix the outdated example folder first.
A few people on reddit where wondering how to use Enzyme / oxide-enzyme,
I don't want to disappoint them with failing examples.
Also, I guess it's fine to remove the (unofficial) note, even if it's not the final codegen integration it's probably the best we have for Rust atm.

**Comment by nestordemeure** [comment]
Ok! I removed the `unofficial` note. I will let you merge when you feel that the time is right.

(Great work with Enzyme! I know it will not happen in the short term but I am hoping that one day I will be able to use it within crates I publish...)

**Review by ZuseZ4 — APPROVED** [review]

**Comment by ZuseZ4** [comment]
@wsmoses This is ready to merge. I'll update the the www branch tomorrow, after having my build code published on [crates.io](https://crates.io/crates/enzyme)

**Comment by ZuseZ4** [comment]
I've updated the www branch, as discussed: https://github.com/wsmoses/Enzyme/pull/400

**Pull request merged**
