### PR TITLE
Update Readme installation instructions

### PR DESCRIPTION
**Pull request by carlocab**
Enzyme was accepted for packaging in Homebrew at https://github.com/Homebrew/homebrew-core/pull/72873.

### CODE REVIEW

**Review by wsmoses — APPROVED** [review]
LGTM and thanks for adding, we might also want to add it to the website (www branch).

Relatedly, what's the process for updating homebrew when a new tag is cut?

**Comment by carlocab** [comment]
Oh yes, instructions on the website would be nice too. I'll have a look later.

To update, just open a PR at https://github.com/Homebrew/homebrew-core, and use the commit message `enzyme 0.0.9` (or whatever your next tag is). 

If you have a Mac with `brew` installed, you can automate the update + PR opening with
```
brew bump-formula-pr --version=$version enzyme
```
You might need to set a GitHub API token in `HOMEBREW_GITHUB_API_TOKEN`, details are in `man brew`. It should also work on Linux, but I think you need to fiddle with some env variables and I'm not familiar with the details.

Or you can fully automate it as part of a release workflow: https://github.com/marketplace/actions/homebrew-bump-formula

**Comment by wsmoses** [comment]
Awesome! Yeah we currently auto-PR julia's package management (https://github.com/wsmoses/Enzyme/blob/main/.github/workflows/tagger.yml) upon a new tag so automating that would be great as well and shouldn't be too hard to integrate.

**Comment by carlocab** [comment]
Cool; it should be super simple then. Here are some relevant example workflows:

https://github.com/ablinov/declutter/blob/master/.github/workflows/bump_homebrew_formula.yml
https://github.com/cloudskiff/driftctl/blob/main/.github/workflows/homebrew.yml
https://github.com/infracost/infracost/blob/master/.github/workflows/create-release.yml#L49-L53
https://github.com/jesseduffield/lazygit/blob/043cb2ea44c9cf899b692e98ff39f1c86e15cb49/.github/workflows/cd.yml#L24-L31
https://github.com/dandavison/delta/blob/0eeb822d0e9e9f340866a8047a0403407acc52d8/.github/workflows/cd.yml#L86-L95

**Pull request merged**
